web:
  environment:
    SERVERNAME: dreamfactory.local
  build: .
  links:
    - mysql:db
    - redis:rd
  ports:
    - "80:80"

mysql:
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: dreamfactory
    MYSQL_USER: df_admin
    MYSQL_PASSWORD: df_admin
  image: mysql

redis:
  image: redis
