version: '2'
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: dreamfactory
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
    image: mysql

  redis:
    image: redis

  web:
    environment:
      SERVERNAME: dreamfactory.local
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: my-secret-pw
      DB_DATABASE: charities
      CACHE_DRIVER: redis
      CACHE_HOST: redis
      CACHE_DATABASE: 0
      CACHE_PORT: 6379
    volumes:
      - df-storage:/opt/dreamfactory/storage
    build: .
    ports:
      - "80:80"
volumes:
  df-storage:
    driver: local
